### ISSUE TITLE
react-native-facetec-zoom [IOS Integration]

### ISSUE THREAD

**Issue by h-ghandour** [tradle/react-native-facetec-zoom#6]
Regarding the integration in IOS i am having some error :
 

![Screen Shot 2019-05-24 at 10 46 51 AM](https://user-images.githubusercontent.com/46043458/58318364-47ca3c00-7e20-11e9-9b92-b78134365077.png)

even tho i did like they stated : 

iOS
This library has been tested with version 7.0.15 of the SDK

First, download ZoomAuthenticationHybrid.framework from one of these sources:

Zoom SDK
app.tradle.io
Unzip the file, locate ZoomAuthenticationHybrid.framework and add it to your project (Copy items if needed should be checked)

Add a Copy File phase to your Xcode project and have ZoomAuthenticationHybrid.framework copied to Destination Frameworks

![Screen Shot 2019-05-24 at 10 50 23 AM](https://user-images.githubusercontent.com/46043458/58318378-4e58b380-7e20-11e9-860d-8ce51c7816a5.png)

any idea why the error is happening ?

**Comment by mvayngrib** [comment]
idk, but in my case i put the `ZoomAuthenticationHybrid.framework` right under `iOS`, and then added it to my project

**Comment by h-ghandour** [comment]
@mvayngrib  
can you provide me with the reproduction steps of what you did exactly to make it to work ?
Like i tried many things still no success here

**Comment by mvayngrib** [comment]
@hassang11 i updated the readme and linked an [example app](https://github.com/tradle/rnzoomexample). I won't have much time to spend on this in the short term so hopefully that's enough to clear things up :)

**Comment by mvayngrib** [comment]
@hassang11 updated the readme and linked an [example app](https://github.com/tradle/rnzoomexample). I won't have much time to spend on this in the short term so hopefully that's enough to clear things up :)

**Comment by h-ghandour** [comment]
@mvayngrib 
Just checked your example
I download and copied ZoomAuthenticationHybrid.framework to ios/ and adjusted in app.js the token like you specified ,but when i tried to run the example app errors popped:
![Screen Shot 2019-05-29 at 8 37 07 AM](https://user-images.githubusercontent.com/46043458/58532129-36e94400-81ed-11e9-874d-99ca423fd67b.png)
xcode files :
![Screen Shot 2019-05-29 at 8 37 20 AM](https://user-images.githubusercontent.com/46043458/58532144-436d9c80-81ed-11e9-9195-2313c55d5cc9.png)

ios directory files :
![Screen Shot 2019-05-29 at 8 37 46 AM](https://user-images.githubusercontent.com/46043458/58532163-508a8b80-81ed-11e9-8d51-83605c0bcd81.png)

**Comment by mvayngrib** [comment]
did you run `yarn` to install dependencies?

**Comment by h-ghandour** [comment]
@mvayngrib yes I did still the same issue 
is the way how i am integrating the issue or something else ?
Is there some sort of information that i can provide you with to help you debug this issue ?

**Comment by mvayngrib** [comment]
@hassang11 idk, i tried setting up the example from the README in a separate directory and it worked fine, even with the latest sdk (7.0.16)
